"use strict";

import {getGameRuntime} from "../game/runtime-access.js";
import {EliteRewardService} from "../game/elite-reward-service.js";

export class RewardView{
 constructor({rewardChoiceList,onRewardSelected}){if(!(rewardChoiceList instanceof HTMLDivElement))throw new Error("La liste des récompenses est invalide.");if(typeof onRewardSelected!=="function")throw new Error("onRewardSelected doit être une fonction.");Object.assign(this,{rewardChoiceList,onRewardSelected});this.currentRound=0;this.selectedItemIds=[];this.service=null;this.encounter=null;}
 render({goldAmount=0}={}){const runtime=getGameRuntime();const context=runtime.gameState?.consumeRunFlag?.("pending-elite-reward-context",null);this.encounter=context?.encounter??{difficulty:2,rewardGold:goldAmount};this.service=new EliteRewardService({gameState:runtime.gameState,itemController:runtime.itemController});this.currentRound=1;this.selectedItemIds=[];this.renderRound();}
 renderRound(){const options=this.service.createRoundOptions(this.encounter,this.selectedItemIds);this.rewardChoiceList.replaceChildren();const summary=document.createElement("p");summary.className="reward-bundle-summary";summary.textContent=`Choix ${this.currentRound} sur 2 — prends l’or ou l’objet. Chance rare : ${Math.round(options.rareChance*100)} %.`;this.rewardChoiceList.append(summary);const grid=document.createElement("div");grid.className="reward-bundle-grid";grid.append(this.createRewardButton(options.gold));if(options.item)grid.append(this.createRewardButton(options.item));else{const empty=document.createElement("article");empty.className="reward-card";empty.textContent="Aucun nouvel objet disponible : l’or reste disponible.";grid.append(empty);}this.rewardChoiceList.append(grid);}
 createRewardButton(reward){const button=document.createElement("button");button.type="button";button.className="reward-choice-button reward-card";if(reward.type==="gold"){const title=document.createElement("strong");title.textContent=`${reward.amount} or`;const detail=document.createElement("span");detail.textContent="Choisir cette récompense";button.append(title,detail);}else{const rarity=reward.item?.rarity==="rare"?"Rare":reward.item?.rarity==="cursed"?"Maudit":"Commun";const title=document.createElement("strong");title.textContent=reward.item?.name??reward.itemId;const description=document.createElement("span");description.textContent=`${rarity} — ${reward.item?.description??"Objet obtenu"}`;button.append(title,description);}button.addEventListener("click",()=>this.selectReward(reward));return button;}
 selectReward(reward){this.disableChoices();const applied=this.service.applyReward(reward);if(!applied){this.enableChoices();return;}if(applied.type==="item")this.selectedItemIds.push(applied.itemId);if(this.currentRound<2){this.currentRound+=1;this.renderRound();return;}this.service.completeElite();this.onRewardSelected({type:"gold",amount:0,eliteRewardComplete:true});}
 disableChoices(){for(const button of this.rewardChoiceList.querySelectorAll("button"))button.disabled=true;}
 enableChoices(){for(const button of this.rewardChoiceList.querySelectorAll("button"))button.disabled=false;}
}
